title: "Prediction on Animal Type"
author: "Elaine Zhou, Jossie Jiang, Swakhar Poddar & Weihao Sun"
date: "2022-4-2"
sphinx:
  config:
    bibtex_reference_style: author_year
execute:
  execute_notebooks: force
bibtex_bibfiles:
    - references.bib
